apiVersion: v1
kind: Service
metadata:
  name: django-ecom-service
  labels:
    app: django-ecom
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: django-ecom
