# Generated by Django 4.1.6 on 2023-10-05 10:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Enter Contact Number', max_length=31),
        ),
    ]
