# Generated by Django 4.1.6 on 2023-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='new_pass',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
