# Generated by Django 4.1.6 on 2023-09-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('hold', 'Hold'), ('closed', 'Closed')], max_length=20, null=True),
        ),
    ]
