# Generated by Django 4.1.6 on 2023-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Hold', 'Hold'), ('Closed', 'Closed')], max_length=20, null=True),
        ),
    ]
