# Generated by Django 4.1.6 on 2023-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remark',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Hold', 'Hold'), ('Closed', 'Closed'), ('Work in Progress', 'Work in Progress')], max_length=20, null=True),
        ),
    ]
