# Generated by Django 4.1.6 on 2023-10-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Suggestion', 'Suggestion')], max_length=10, null=True),
        ),
    ]
