# Generated by Django 4.1.6 on 2023-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='experience',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], max_length=10, null=True),
        ),
    ]
