# Generated by Django 4.1.6 on 2023-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_feedback_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
