# Generated by Django 4.1.6 on 2023-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_remove_feedback_priority_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Hold', 'Hold'), ('Closed', 'Closed'), ('Work in Progress', 'Work in Progress')], default='Open', max_length=20, null=True),
        ),
    ]
