# Generated by Django 4.1.6 on 2023-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remark',
            field=models.TextField(blank=True, default='No Remarks', max_length=300, null=True),
        ),
    ]
